### ISSUE TITLE
question about loss function

### ISSUE THREAD

**Issue by JayC1208** [nlp-tlp/cyle#1]
So in the calculation of distance score, the lower bound and the upper bound is obtained by the subtraction or addition of theta_ax and (theta_ap)/2, but in the code, just original (theta_ap) is used. 

how come? can you give more explanation about this?

Thanks

**Comment by chaundm** [comment]
Hi, theta_ap at that time is obtained after going through the relation projection, and it's already converted to half of aperture (using convert to arg function) in the projection process, Best

**Comment by JayC1208** [comment]
okay thanks for the fast reply! than can you give info about angle scale class and way to setting up the value of embedding range?  what does (gamma+epsilon)/hidden size indicate?

**Comment by chaundm** [comment]
The class is to scale value of an input based on its embedding dimension (for numerical stability), and the hidden size above is the embedding dimension (d)
